### ISSUE TITLE
LiveTV streaming issues outside NL

### ISSUE THREAD

**Issue by pradix** [4np/UitzendingGemist#22]
Hi,

Before 1st of March everything was working great. Watching TV outside Netherlands (I'm based in Dubai). Since the changes made by you and or NPO on the backend it's not working anymore. 
Streaming tv shows are still working great, but watching liveTV is not working.
If I look in the logs what i'm getting back i see the following:

2017-03-17 21:48:00:406 UitzendingGemist[4239:2601290] Could not play live stream (Optional(NPOKit.NPOError.networkError("Could not fetch live stream url (url: https://livestreams.omroep.nl/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=6b2bf994a10ca639a843f939f66a8d9b&type=jsonp&protection=url) (3)")))

Feedback if you open the url is as follow: This is a protected url but hash incorrect or missing, uri: /index.php/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=6b2bf994a10ca639a843f939f66a8d9b&type=jsonp&protection=url

If I use the website of NPO.nl everything is working, i'm using a SmartDNS services such as Unotelly 
and or Unlocator and I have just tested and everything is working on the website.

This is the same URL if I watch NPO1 on their website:
https://smoote1a.omroep.nl/urishieldv2/l2cm22de7f5c460058cc22a7000000.88799773542a1c83/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8

This is the NPO2 live stream through their website:
https://smoote1a.omroep.nl/urishieldv2/l2cm05c65ef2370058cc235a000000.7c77b08c225fad59/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8

 So I think it's something small to fix in the backend of your application. I have installed 1.4.1 version

**Comment by DutchDude69** [comment]
Hi,

Also when used inside The Netherlands with a smart DNS service the VOD streaming stopped working.
Only showing a black screen with a small red stop sign in the left bottom of the screen.
The live TV is still working.
It looks like its related to the smart DNS service, because all works fine when I change the used DNS to my ISP (ziggo) DNS. But then all my US apps stop working ;-)

Strange thing is that on my PC using the same smart DNS settings, all is working fine.
Is the ATV app using a different backend?
 
I tested with 1.4.0 & 1.4.1

**Comment by 4np** [comment]
I have pushed a couple of changes to the logic that fetches the live stream urls that -_i think_- could solve the issues you are having. Can you please try again with the latest code and see if it solves the issues you are having?

**Comment by 4np** [comment]
I just released [1.5.0](https://github.com/4np/UitzendingGemist/releases/tag/1.5.0) which brings several video stream improvements and adds support for closed captioning.

**Comment by 4np** [comment]
@pradix : Did you manage to test the latest release? Are things working properly for you now?

**Comment by pradix** [comment]
Can't look into it now I'm traveling. I'm back on Monday and will test it. Thank you!!

**Comment by 4np** [comment]
Cool, thanks! Happy traveling :)

**Comment by pradix** [comment]
I have tested, but didn't solve the problems.
In logs i get: 2017-03-27 13:18:52.049 UitzendingGemist[11692:5024041] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

This is the link on the website of NPO that's working at the moment what i'm using with SmartDNS server: https://smoote1d.omroep.nl/urishieldv2/l2cm8da084a61c0058d8daa5000000.f5efc6d1721a0c10/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8

In previous version 1.4 i still could even watch programs outside Netherlands, now you have blocked that option. I'm using smartDNS server Unlocator and Unotelly. If it's needfull i can share it in private message my account. 

Everyhing on the iPad works fine with the NPO app.

**Comment by 4np** [comment]
That's not the news I was expecting, can you do some more debugging on your end? The tvOS app is actually using those URLs you are seeing :) If you use Chrome's network debugger getting the URL is actually a three-step process. For example:

### Go to an episode

For example to [this episode](https://www.npo.nl/floortje-naar-het-einde-van-de-wereld/26-03-2017/VARA_101381746)

### Inspect the requests and search for the one that returns the different video content types (the app is currently _always_ using the adaptive one)

![step1](https://cloud.githubusercontent.com/assets/1049693/24369173/697effa8-1323-11e7-82a8-e193286b8aed.jpg)

### Inspect the JSONP request to the adaptive playlist

![step2and3](https://cloud.githubusercontent.com/assets/1049693/24369205/8572b4ca-1323-11e7-9a17-ea9011342344.jpg)

### That will lead to the final playlist that the video player will use

![step3](https://cloud.githubusercontent.com/assets/1049693/24369220/922bd35e-1323-11e7-86d3-139e197c531a.jpg)

_Note that the app will currently perform a different call for step 2 getting rid of the *jsonp* and *callback* parameters which will immediately return the result from step 3. So right now, the app uses two requests to obtain the video playlist._

## Another thing to try...

The App will now use stream types in order of preference. You can try to change the order [like described here](https://github.com/4np/UitzendingGemist/issues/21#issuecomment-288241271). Perhaps that will allow you to pinpoint the issue?

**Comment by pradix** [comment]
Floortje was not geo blocked so already working.
It's the live streaming that is not working and i can't play for now the geo blocked episodes (maybe you can make the play button still clickable)

**Comment by pradix** [comment]
I disabled the geo restrictions on my side in your app...all the streams are working. The only thing that's not working is the live streams. In de debugging it give it's paused. I have played around with the quality, that don't make any difference. For the normal streams the adaptive is even playing!
So the only issue i have is live streaming (on the NPO site it's working)

**Comment by 4np** [comment]
Aha, it was not clear from your previous post that the episodes with no-region validation were still playing as expected but that those that _did have_ region limitation did not play. To re-enable the button (basically ignoring the region check) you can change [this line](https://github.com/4np/UitzendingGemist/blob/master/UitzendingGemist/EpisodeViewController.swift#L301) as follows:

```
playButton.isEnabled = true //canPlay
```

I would suspect that those episodes that are marked to have region limitation will still not play, even if you enable the button. It might be similar for those live feeds, perhaps they are regionally limited now as well.

Regarding _Unlocator_, their FAQ states the following:

```
Unlike traditional VPN tunnels we only redirect the traffic responsible for geographic detection. 
```

To me, that sounds very unlikely / too good to be true. Whenever you connect to a streaming video server, your IP is known _or_ they have to route the video stream through their VPN (which they say they don't).

**Comment by pradix** [comment]
I looked in your source code NPOManager+Streams.swift: 

This is the url that i got on chrome while i'm watching NPO1 Live: 
https://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=no&token=pd91k0014qft7caaju725282v1
with output: 
{"limited":false,"site":null,"items":[[{"label":"Live","contentType":"live","url":"https:\/\/livestreams.omroep.nl\/live\/npo\/tvlive\/npo1\/npo1.isml\/npo1.m3u8?hash=5a358f2d687806d71c273113d4344b15&type=jsonp&protection=url","format":"hls"}]]}

**Comment by 4np** [comment]
The geo check that determine whether or not the play button is enabled is using an open source project. What country does [this url](http://freegeoip.net/json/) report back to you?

**Comment by pradix** [comment]
I found the solution: it's the token that is wrong: if i change the token: pd91k0014qft7caaju725282v1
Than it's working
https://ida.omroep.nl/app.php/LI_NL2_4188105?adaptive=no&token=pd91k0014qft7caaju725282v1
This was the output from your app - token: 40b25u9q5bc3pe7aovv94u75m2 
https://ida.omroep.nl/app.php/LI_NL2_4188105?adaptive=yes&token=40b25u9q5bc3pe7aovv94u75m2

**Comment by 4np** [comment]
That's strange, as the token has a lifetime of 2 hours (7200 seconds, that app expires the token sooner in 1 hour). What happens if you set the token lifetime to 0 in [this file](https://github.com/4np/UitzendingGemist/blob/2a62b1d7fe65877832df3bd81c71c6fcba3297f2/NPOKit/NPOKit/NPOToken.swift#L14)?

I am unable to open the URLs you posted:

```
{
"error": "Access denied"
}
```

It looks like the token is based on your IP address... Perhaps that is causing the issue?

**Comment by pradix** [comment]
makes no difference.
only weird thing is:
when I use https i get this as output:
(Optional(NPOKit.NPOError.networkError("Could not fetch stream for video model (url: https://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=yes&token=0ae9va9b2o9m5dcit0ah6eag31)")))
if i copy the link in browser and remove the https and replace it with http, it's working.
http://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=yes&token=0ae9va9b2o9m5dcit0ah6eag31
When i change it back in the code to http. than it's not working.
i have feeling we are almost there ;-)

**Comment by 4np** [comment]
Hmm, it seems like [my comment](https://github.com/4np/UitzendingGemist/blob/570bf432c1fb4a498045a0e39845c958682e2f38/NPOKit/NPOKit/NPOManager%2BStream.swift#L86) says https while the url says http... in general I should really get rid of the http and only use https whenever possible. Apple has been _allowing_ it but they will most likely [kill the non-secure transports altogether sooner than later](https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/).

**Comment by pradix** [comment]
What can we do to fix this issue? i need to watch Studio Sport on Sunday ;-)

**Comment by 4np** [comment]
Hahahahaha :D

**Comment by pradix** [comment]
I'm not getting any error in the debugger, but only that it's paused, even when i try to play with the order of the video quality:
2017-03-27 23:06:42:827 UitzendingGemist[19233:5360228] Debugging episode video player is enabled
2017-03-27 23:06:42:839 UitzendingGemist[19233:5360228] Player is now waiting to play at the specified rate
2017-03-27 23:07:02:904 UitzendingGemist[19233:5360228] Player is now paused

**Comment by pradix** [comment]
i tried to add you on skype...that talk quicker

**Comment by 4np** [comment]
I just pushed another change and I changed all URLs from http to https. The back-end did not use https and looking at the certificate they added https support in dec 2016. Probably to prepare for Apple closing down on http resources...

**Comment by 4np** [comment]
Finally we managed to solve the issue :D

**Comment by pradix** [comment]
Thanks for all your support

**Comment by 4np** [comment]
Finalized support in the [1.5.1 release](https://github.com/4np/UitzendingGemist/releases/tag/1.5.1)
